<form class="log-in-form" method="post" action="<?php echo App::config("url")?>admin/login">

    <label>Email
        <input type="email" name="email" placeholder="maja.balas@gmail.com"
            value="<?php echo Request::post("email") ?>">
    </label>
    <label>Password
        <input type="password" name="password" placeholder="m">
    </label>

    <p><input type="submit" class="button expanded" value="Log in" /></p>

</form>

<?php echo $poruka ?>